### PR TITLE
fixed some bugs in the current version

### PR DESCRIPTION
**Pull request by mromanello**

### CODE REVIEW

**Comment by cosminbasca** [comment]
Hi @mromanello could you please provide a description of the fix and what the original problem was and why it happened? Thank you!

**Comment by mromanello** [comment]
I fixed two different problems:

1. in files `plugins/surf.rdflib/setup.py` and `plugins/surf.sparql_protocol/setup.py` the `install_requires` parameter was not synchronised with the current version of surf (should be 'surf>=0.1.8' instead of 'surf>=1.1.5)

2. in `plugins/surf.rdflib/surf_rdflib/reader.py` there was an issue related to the JSON serialization of the query result -- I believe this is due to changes in RDFLib 4.x as opposed to 3.x. 

(Would this be enough? )

**Comment by cosminbasca** [comment]
Sounds good, thanks for the description. I will review the changes later this week. Cheers!

**Comment by cosminbasca** [comment]
The source of the error was a version bump typo fixed in  c141cc5ec94be2a85466aa2b3a77828886aedbf8. Could you please create another PR containing only the return loads(result.serialize(format='json')) change? Thanks

**Comment by cosminbasca** [comment]
I am closing this PR as bumping down the version due to a bug is not a solution

**Comment by mromanello** [comment]
Hi! I've just opened a PR only with that change, hope I did it the right way ;-) cheers

**Pull request closed without merging**
