### PR TITLE
Python3 support - non-working

### PR DESCRIPTION
**Pull request by funkyfuture**
okay, here's an intitial attempt to solve #5.

i'm stuck with it right now and am rather confused what's causing the fails. it affects both Python 2 and 3. i guess you may better figure out what's wrong as the code is rather grown and complex. i also have the suspicion that one cause may be a bug in rdflib.

oops, i also commited changes to `ez_setup.py`, but this is a whole mess and obsolete anyway.

### CODE REVIEW

**Comment by funkyfuture** [comment]
oh, and .travis.yml needs adjustments.

**Comment by cosminbasca** [comment]
I will take a look at it, but it will take some time as I have less of it these days :), thanks !

**Comment by wikier** [comment]
any news on this? can I help with something?

**Comment by cosminbasca** [comment]
no progress on this one from my side, little time lately to focus on SuRF, any help with it is much appreciated, thx @wikier !

**Comment by mromanello** [comment]
hi @cosminbasca do you have an idea of what's the issue with @funkyfuture's code for porting `surf` to py3? I'd be happy to take it from where he left it, but don't know the codebase that well. So any hints/advices about where to start from would be much appreciated.

**Pull request closed without merging**
